
version: 2

models:
   
  - name: stock_metrics
    description: "Metrics derived from stock analysis"
    columns:
      - name: symbol
        description: "Ticker symbol of the stock"
        tests:
          - not_null
      - name: close
        description: "Closing price of the stock"
        tests:
          - not_null
